# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Finance App Build and Deploy

on: workflow_dispatch

jobs:        
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Dist
        uses: actions/download-artifact@v3
        with:
          name: dist
      - run: cd finance-app
      - run: pwd
      - run: cd finance-app
      - run: pwd
      - name: Fly Deploy
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
